#!/usr/bin/env node
// build-catalog — regenerate CATALOG.md from the per-template frontmatter.
//
// Each templates/<slug>/design.md carries a `catalog:` block (level / formality /
// vibe / signature). This script reads them all and rewrites CATALOG.md so the table
// is never hand-maintained: add a template folder with a catalog block, run this, done.
//
// Usage:  node scripts/build-catalog.mjs [--check]
//   --check   exit 1 if CATALOG.md is out of date (for CI / pre-commit), don't write.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const TEMPLATES = join(ROOT, "templates");
const CATALOG = join(ROOT, "CATALOG.md");
const LEVELS = ["Restrained", "Balanced", "Bold"];

// Pull the YAML frontmatter (first block between --- fences).
function frontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---/);
  if (!m) throw new Error("no frontmatter");
  return m[1];
}

// Targeted parse — we only need name + the catalog: sub-block.
function parse(slug, md) {
  const fm = frontmatter(md);
  const name = fm.match(/^name:\s*(.+)$/m)?.[1].trim();
  if (!name) throw new Error(`${slug}: missing name`);

  const cat = fm.match(/^catalog:\n([\s\S]*?)(?=^\S)/m);
  if (!cat) throw new Error(`${slug}: missing catalog: block`);
  const block = cat[1];

  const field = (k) => block.match(new RegExp(`^  ${k}:\\s*(.+)$`, "m"))?.[1].trim();
  const level = field("level");
  const formality = field("formality");
  const vibe = field("vibe");
  const signature = [...block.matchAll(/^\s+-\s*"(.+?)"\s*$/gm)].map((m) => m[1].trim());

  for (const [k, v] of Object.entries({ level, formality, vibe })) {
    if (!v) throw new Error(`${slug}: missing catalog.${k}`);
  }
  if (!LEVELS.includes(level)) throw new Error(`${slug}: bad level "${level}"`);
  if (!signature.length) throw new Error(`${slug}: empty catalog.signature`);

  return { slug, name, level, formality, vibe, signature };
}

const rows = readdirSync(TEMPLATES, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => parse(e.name, readFileSync(join(TEMPLATES, e.name, "design.md"), "utf8")))
  .sort((a, b) => a.name.localeCompare(b.name));

const esc = (s) => s.replace(/\|/g, "\\|");
function table(level) {
  const r = rows.filter((x) => x.level === level);
  const head =
    "| Style | Formality | Vibe | Palette (canvas · accents) |\n" +
    "| ----- | --------- | ---- | -------------------------- |";
  const body = r
    .map(
      (x) =>
        `| [${esc(x.name)}](templates/${x.slug}/) | ${x.formality} | ${esc(x.vibe)} | ${x.signature
          .map((s) => `\`${s}\``)
          .join(" · ")} |`
    )
    .join("\n");
  return `${head}\n${body}`;
}

const md = `# Style Catalogue

<!-- GENERATED by scripts/build-catalog.mjs from templates/*/design.md — do not edit by hand. -->

Use this to pick a style for the user, by the **level** (how restrained or bold it feels), the
**formality**, and the **vibe** they want. Any style can carry almost any content, so choose by feel.
If the user named a style or a clear preference, honour it. Otherwise infer from the tone they want.
After generating, always tell the user they can switch to any other style.

Each row lists its **palette signature** (canvas + the defining accents, as hex) so you can choose
from this table **alone**. Once you pick a style, open **only that one** \`templates/<slug>/design.md\`
for the full colour notes — do not open several templates to compare.

The ${rows.length} styles are grouped into three levels, from restrained to bold:

- **Restrained** — calm, muted, often monochrome; for serious, quiet, editorial boards.
- **Balanced** — a confident accent or two on a clean ground; the versatile middle. Most work lives here.
- **Bold** — loud, saturated, lots of colour; for playful, high-energy, attention-grabbing boards.

**Formality key:** **Low** = playful / casual, **Medium** = confident / modern, **High** =
restrained / refined / institutional.

## Restrained

${table("Restrained")}

## Balanced

${table("Balanced")}

## Bold

${table("Bold")}

## How to choose

1. **Level first.** How loud should the board feel? Quiet / serious leans **Restrained**; playful or
   high-energy leans **Bold**; most general work sits comfortably in **Balanced**.
2. **Formality second.** Within the level, match how formal it should read (Low / Medium / High).
3. **Vibe third.** Narrow by the user's mood or colour preference (the Vibe + Palette columns).
4. **When unsure, default to a safe or balanced style.**
5. **Commit from this table, then open exactly one \`design.md\`** — the one for the style you picked.
   The palette signature here is enough to choose; don't open several templates to compare.
6. Always offer to switch afterwards. Swapping style means re-rendering the same content in a
   different template's palette.
`;

const current = (() => {
  try {
    return readFileSync(CATALOG, "utf8");
  } catch {
    return "";
  }
})();

if (process.argv.includes("--check")) {
  if (current !== md) {
    console.error("CATALOG.md is out of date — run: node scripts/build-catalog.mjs");
    process.exit(1);
  }
  console.log(`CATALOG.md up to date (${rows.length} styles).`);
} else {
  writeFileSync(CATALOG, md);
  console.log(`Wrote CATALOG.md (${rows.length} styles: ${rows.map((r) => r.name).join(", ")}).`);
}
